### ISSUE TITLE
Erreur lors du lancement de l'application

### ISSUE THREAD

**Issue by Hugman76** [juanluck/lampDocker#1]
Lors de l'exécution de `docker run -p 8000:80 debian-lamp`, le programme retourne :
"/bin/sh: 1: /root/start-script.sh: not found"

Sous Windows 11

**SOLUTION** :
Pour régler ce problème, il suffit de changer le format des retours à la ligne du fichier `start-script.sh`.
Sous Visual Studio Code/IntelliJ Idea, en bas à droite de l'interface, cliquez sur "CRLF", une popup s'ouvrira. Changez le format à "LF".
Cela est dû au fait que le format CRLF est propre à Windows, et n'est pas reconnaissable par Ubuntu.
Pour plus d'informations : https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

**Comment by Eldaon** [comment]
Même soucis sous machine personnelle Window

**Comment by juanluck** [comment]
Pouvez-vous essayer à changer la ligne suivante du dockerfile : 
COPY start-script.sh /root/
par :
COPY ./start-script.sh /root/

Permettez-moi de savoir si cela fonctionne

**Comment by Hugman76** [comment]
Après plusieurs autres manipulations d'images docker et la réinstallation du dépôt sur ma machine, l'erreur s'est fixée sans avoir besoin de votre correctif.

**Comment by Hugman76** [comment]
Cependant mon collègue est tombé sur ce soucis, je vous ferais part de son retour dès qu'il sera à nouveau en mesure d'éxecuter la commande

**Comment by Louis-Hagues** [comment]
Je ne peux pas run le docker pour la même raison qu'Hugman76 vous a signalé en ayant fait un réinstallation de l'image et le correctif.

**Comment by juanluck** [comment]
Je serai à l'IUT à partir de 13h30. On peut le voir ensemble.

**Comment by Louis-Hagues** [comment]
Bien sûr je suis en 702

**Comment by Hugman76** [comment]
J'ai mis à jour mon ticket original (haut de cette page) avec la solution.
